### ISSUE TITLE
Not all folders are showing up

### ISSUE THREAD

**Issue by Zephancode** [kenlim/obsidian-file-chucker#1]
When I try and use it I only get a certain number of the top folders. Upon adding the name of the maps etc it still doesn't show up. If I fully type out the name, the file does get moved to the correct folder.

**Comment by Zephancode** [comment]
It might have been related to the folders not having a file already in them / being freshly created.

**Comment by kenlim** [comment]
Congratulations! You're the first issue!

Unfortunately, it looks like Obsidian's default behaviour is to ignore empty folders, which is why you cannot see folders in the fuzzy search dropdown. 

I believe you have a few options:

### 1. Do not create empty folders.
Instead, use the file-chucker to create them when you need them. With Tab-completion, you don't have to type the whole path of your folder!

For example, if your target folder is: "/Programming/Javascript/Testing" and you already have the folders "/Programming/Javascript" created.

just type "java" into the fuzzy searchbox. Then use the arrow keys to select "/Programming/Javascript" and press the TAB key. The whole path will be filled in the drop down!

Then finish the path by typing in "/Testing", then press ENTER to create and move the file there.

### 2. Use a plugin that creates a "default" file in a folder
I currently use Folder Note, but you'll have to still manually create the "Folder Note" everytime you make a new folder. 

Hope you're enjoying file-chucker!

**Comment by simonmichael** [comment]
This is a pretty surprising behaviour. Any chance of a fix ?
